[build]
  command = "npm run build"
  publish = "build"
  functions = "functions"
  [build.environment]
    CI = "false"

[dev]
  framework = "#auto"
  targetPort = 3002
  port = 8888
  functionsPort = 8889
  autoLaunch = true

# Redirect API requests to Netlify Functions proxy
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/proxy/:splat"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
