import React from 'react';
import { useNavigate } from 'react-router-dom';

const Privacy = () => {
  const navigate = useNavigate();

  return (
    <div className="bg-primary-light pt-20 min-h-screen">
      {/* Header Section */}
      <div
        className="relative w-full h-40 bg-cover bg-center flex items-center justify-center"
        style={{ backgroundImage: `url('../images/3rd-Home-main.png')` }}
      >
        <div className="absolute inset-0 bg-black bg-opacity-60"></div>
        <h1 className="relative z-10 text-4xl md:text-5xl font-gilroy-semibold text-white">
          Privacy Policy
        </h1>
      </div>

      {/* Breadcrumb Navigation */}
      <div
        className="px-5 py-5 font-gilroy-semibold text-base cursor-pointer hover:text-primary-green transition-colors"
        onClick={() => navigate('/')}
      >
        Home › Privacy Policy
      </div>

      {/* Privacy Policy Content */}
      <div className="container mx-auto px-4 md:px-8 py-8 mb-16">
        <div className="max-w-4xl mx-auto bg-white rounded-lg shadow-sm p-6 md:p-10">
          <h1 className="text-3xl font-gilroy-semibold text-primary-dark mb-6">
            Privacy Policy
          </h1>

          <p className="mb-4 text-gray-700">
           
        Terms & Conditions
1.	This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
2.	This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name https://asikhfarms.in/ ('Website'), including the related mobile site and mobile application (hereinafter referred to as 'Platform').
3.	The Platform is owned by OM ENTERPRISE, a company incorporated under the Companies Act, 1956 with its registered office at KH. 314, PLOT-I-IA, JAFFARPUR EXTN. NAJAFGARH.NEW DELHI, south west Delhi. Delhi, 1 110073 (hereinafter referred to as ‘Platform Owner’, 'we', 'us', 'our')..
4.	Your use of the Platform and services and tools are governed by the following terms and conditions (“Terms of Use”) as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations, with Platform Owner. These Terms of Use relate to your use of our website, goods (as applicable) or services (as applicable) (collectively, 'Services'). Any terms and conditions proposed by You which are in addition to or which conflict with these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect. These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay informed of updates..
5.	For the purpose of these Terms of Use, wherever the context so requires ‘you’, 'your' or ‘user’ shall mean any natural or legal person who has agreed to become a user/buyer on the Platform..
6.	ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING..
7.	The use of Platform and/or availing of our Services is subject to the following Terms of Use:
1.	To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform..
2.	Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website or through the Services, for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law..
3.	Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements..
4.	The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The contents includes and is not limited to the design, layout, look and graphics..
5.	You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws..
6.	You agree to pay us the charges associated with availing the Services..
7.	You agree not to use the Platform and/ or Services for any purpose that is unlawful, illegal or forbidden by these Terms, or Indian or local laws that might apply to you.
8.	You agree and acknowledge that website and the Services may contain links to other third party websites. On accessing these links, you will be governed by the terms of use, privacy policy and such other policies of such third party websites. These links are provided for your convenience for provide further information..
 
9.	You understand that upon initiating a transaction for availing the Services you are entering into a legally binding and enforceable contract with the Platform Owner for the Services..
10.	You shall indemnify and hold harmless Platform Owner, its affiliates, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorney's fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.
11.	Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event..
12.	These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India..
13.	All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in Nagpur and Maharashtra.
14.	All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website
 
Privacy Policy
Introduction
This Privacy Policy describes how OM ENTERPRISE and its affiliates (collectively " OM ENTERPRISE, we, our, us") collect, use, share, protect or otherwise process your information/ personal data through our website https://asikhfarms.in/ (hereinafter referred to as Platform). Please note that you may be able to browse certain sections of the Platform without registering with us.We do not offer any product/service under this Platform outside India and your personal data will primarily be stored and processed in India. By visiting this Platform, providing your information or availing any product/service offered on the Platform, you expressly agree to be bound by the terms and conditions of this Privacy Policy, the Terms of Use and the applicable service
/product terms and conditions, and agree to be governed by the laws of India including but not limited to the laws applicable to data protection and privacy. If you do not agree please do not use or access our Platform.
Collection-We collect your personal data when you use our Platform, services or otherwise interact with us during the course of our relationship.and related information provided from time to time. Some of the information that we may collect includes but is not limited to personal data / information provided to us during sign-up/registering or using our Platform such as name, date of birth, address, telephone/mobile number, email IDand/or any such information shared as proof of identity or address. Some of the sensitive personal data may be collected with your consent, such as your bank account or credit or debit card or other payment instrument information or biometric information such as your facial features or physiological information (in order to enable use of certain features when opted for, available on the Platform) etc all of the above being in accordance with applicable law(s) You always have the option to not provide information, by choosing not to use a particular service or feature on the Platform. We may track your behaviour, preferences, and other information that you choose to provide on our Platform.
This information is compiled and analysed on an aggregated basis. We will also collect your information related to your transactions on Platform and such third-party business partner platforms. When such a third-party business partner collects your personal data directly from you, you will be governed by their privacy policies. We shall not be responsible for the third-party business partner’s privacy practices or the content of their privacy policies, and we request you to read their privacy policies prior to disclosing any information. If you receive an email, a call from a person/association claiming to be OM ENTERPRISE seeking any personal data like debit/credit card PIN, net-banking or mobile banking password, we request you to never provide such information. If you have already revealed such information, report it immediately to an appropriate law enforcement agency.

Usage- We use personal data to provide the services you request. To the extent we use your personal data to market to you, we will provide you the ability to opt-out of such uses. We use your personal data to assist sellers and business partners in handling and fulfilling orders; enhancing customer experience; to resolve disputes; troubleshoot problems; inform you about online and offline offers, products, services, and updates; customise your experience; detect and protect us against error, fraud and other criminal activity; enforce our terms and conditions; conduct marketing research, analysis and surveys; and as otherwise described to you at the time of collection of information. You understand that your access to these products/services may be affected in the event permission is not provided to us.

Sharing- We may share your personal data internally within our group entities, our other corporate entities, and affiliates to provide you access to the services and products offered by them. These entities and affiliates may market to you as a result of such sharing unless you explicitly opt-out. We may disclose personal data to third parties such as sellers, business partners, third party service providers including logistics partners, prepaid payment instrument issuers, third-party reward programs and other payment opted by you. These disclosure may be required for us to provide you access to our services and products offered to you, to comply with our legal obligations, to enforce our user agreement, to facilitate our marketing and advertising activities, to prevent, detect, mitigate, and investigate fraudulent or illegal activities related to our services. We may disclose personal and sensitive personal data to government agencies or other authorised law enforcement agencies if required to do so by law or in the good faith
 
belief that such disclosure is reasonably necessary to respond to subpoenas, court orders, or other legal process. We may disclose personal data to law enforcement offices, third party rights owners, or others in the good faith belief that such disclosure is reasonably necessary to: enforce our Terms of Use or Privacy Policy; respond to claims that an advertisement, posting or other content violates the rights of a third party; or protect the rights, property or personal safety of our users or the general public.

Security Precautions- To protect your personal data from unauthorised access or disclosure, loss or misuse we adopt reasonable security practices and procedures. Once your information is in our possession or whenever you access your account information, we adhere to our security guidelines to protect it against unauthorised access and offer the use of a secure server. However, the transmission of information is not completely secure for reasons beyond our control. By using the Platform, the users accept the security implications of data transmission over the internet and the World Wide Web which cannot always be guaranteed as completely secure, and therefore, there would always remain certain inherent risks regarding use of the Platform. Users are responsible for ensuring the protection of login and password records for their account.

Data Deletion and Retention- You have an option to delete your account by visiting your profile and settings on our Platform , this action would result in you losing all information related to your account. You may also write to us at the contact information provided below to assist you with these requests. We may in event of any pending grievance, claims, pending shipments or any other services we may refuse or delay deletion of the account. Once the account is deleted, you will lose access to the account. We retain your personal data information for a period no longer than is required for the purpose for which it was collected or as required under any applicable law. However, we may retain data related to you if we believe it may be necessary to prevent fraud or future abuse or for other legitimate purposes. We may continue to retain your data in anonymised form for analytical and research purposes.

Your Rights- You may access, rectify, and update your personal data directly through the functionalities provided on the Platform.

Consent- By visiting our Platform or by providing your information, you consent to the collection, use, storage, disclosure and otherwise processing of your information on the Platform in accordance with this Privacy Policy. If you disclose to us any personal data relating to other people, you represent that you have the authority to do so and permit us to use the information in accordance with this Privacy Policy. You, while providing your personal data over the Platform or any partner platforms or establishments, consent to us (including our other corporate entities, affiliates, lending partners, technology partners, marketing channels, business partners and other third parties) to contact you through SMS, instant messaging apps, call and/or e-mail for the purposes specified in this Privacy Policy. You have an option to withdraw your consent that you have already provided by writing to the Grievance Officer at the contact information provided below. Please mention “Withdrawal of consent for processing personal data” in your subject line of your communication. We may verify such requests before acting on our request. However, please note that your withdrawal of consent will not be retrospective and will be in accordance with the Terms of Use, this Privacy Policy, and applicable laws. In the event you withdraw consent given to us under this Privacy Policy, we reserve the right to restrict or deny the provision of our services for which we consider such information to be necessary.

Changes to this Privacy Policy- Please check our Privacy Policy periodically for changes. We may update this Privacy Policy to reflect changes to our information practices. We may alert / notify you about the significant changes to the Privacy Policy, in the manner as may be required under applicable laws.
 


          </p>

          <ul className="list-disc pl-6 mb-4 text-gray-700">
            <li className="mb-2">
              Visit our website at http://www.asikhfarms.in, or any website of
              ours that links to this Privacy Notice
            </li>
            <li className="mb-2">
              Engage with us in other related ways, including any sales,
              marketing, or events
            </li>
          </ul>

          <p className="mb-6 text-gray-700">
          Shipping policy and returns and refunds- shipping takes 7-8 days and no returns or refunds
          </p>

          <h2 className="text-2xl font-gilroy-semibold text-primary-dark mt-8 mb-4">
            SUMMARY OF KEY POINTS
          </h2>

          <p className="mb-4 text-gray-700">
            This summary provides key points from our Privacy Notice, but you
            can find out more details about any of these topics by clicking the
            link following each key point or by using our table of contents
            below to find the section you are looking for.
          </p>

          <p className="mb-4 text-gray-700">
            What personal information do we process? When you visit, use, or
            navigate our Services, we may process personal information depending
            on how you interact with us and the Services, the choices you make,
            and the products and features you use. Learn more about personal
            information you disclose to us.
          </p>

          <p className="mb-4 text-gray-700">
            Do we process any sensitive personal information? Some of the
            information may be considered 'special' or 'sensitive' in certain
            jurisdictions, for example your racial or ethnic origins, sexual
            orientation, and religious beliefs. We do not process sensitive
            personal information.
          </p>

          <p className="mb-4 text-gray-700">
            Do we collect any information from third parties? We do not collect
            any information from third parties.
          </p>

          <p className="mb-4 text-gray-700">
            How do we process your information? We process your information to
            provide, improve, and administer our Services, communicate with you,
            for security and fraud prevention, and to comply with law. We may
            also process your information for other purposes with your consent.
            We process your information only when we have a valid legal reason
            to do so. Learn more about how we process your information.
          </p>

          <p className="mb-4 text-gray-700">
            In what situations and with which parties do we share personal
            information? We may share information in specific situations and
            with specific third parties. Learn more about when and with whom we
            share your personal information.
          </p>

          <p className="mb-4 text-gray-700">
            How do we keep your information safe? We have adequate
            organisational and technical processes and procedures in place to
            protect your personal information. However, no electronic
            transmission over the internet or information storage technology can
            be guaranteed to be 100% secure, so we cannot promise or guarantee
            that hackers, cybercriminals, or other unauthorised third parties
            will not be able to defeat our security and improperly collect,
            access, steal, or modify your information. Learn more about how we
            keep your information safe.
          </p>

          <p className="mb-4 text-gray-700">
            What are your rights? Depending on where you are located
            geographically, the applicable privacy law may mean you have certain
            rights regarding your personal information. Learn more about your
            privacy rights. How do you exercise your rights? The easiest way to
            exercise your rights is by submitting a data subject access request,
            or by contacting us. We will consider and act upon any request in
            accordance with applicable data protection laws.
          </p>

          <p className="mb-6 text-gray-700">
            Want to learn more about what we do with any information we collect?
            Review the Privacy Notice in full.
          </p>

          <h2 className="text-2xl font-gilroy-semibold text-primary-dark mt-8 mb-4">
            TABLE OF CONTENTS
          </h2>

          <ol className="list-decimal pl-6 mb-6 space-y-2 text-gray-700">
            <li>WHAT INFORMATION DO WE COLLECT?</li>
            <li>HOW DO WE PROCESS YOUR INFORMATION?</li>
            <li>WHEN AND WITH WHOM DO WE SHARE YOUR PERSONAL INFORMATION?</li>
            <li>DO WE USE COOKIES AND OTHER TRACKING TECHNOLOGIES?</li>
            <li>HOW LONG DO WE KEEP YOUR INFORMATION?</li>
            <li>HOW DO WE KEEP YOUR INFORMATION SAFE?</li>
            <li>WHAT ARE YOUR PRIVACY RIGHTS?</li>
            <li>CONTROLS FOR DO-NOT-TRACK FEATURES</li>
            <li>DO WE MAKE UPDATES TO THIS NOTICE?</li>
            <li>HOW CAN YOU CONTACT US ABOUT THIS NOTICE?</li>
            <li>
              HOW CAN YOU REVIEW, UPDATE, OR DELETE THE DATA WE COLLECT FROM
              YOU?
            </li>
          </ol>

          <h2 className="text-xl font-gilroy-semibold text-primary-dark mt-8 mb-4">
            1. WHAT INFORMATION DO WE COLLECT?
          </h2>

          <p className="font-medium mb-2 text-gray-800">
            Personal information you disclose to us
          </p>

          <p className="mb-4 text-gray-700">
            In Short: We collect personal information that you provide to us.
          </p>

          <p className="mb-4 text-gray-700">
            We collect personal information that you voluntarily provide to us
            when you express an interest in obtaining information about us or
            our products and Services, when you participate in activities on the
            Services, or otherwise when you contact us.
          </p>

          <p className="mb-4 text-gray-700">
            Personal Information Provided by You. The personal information that
            we collect depends on the context of your interactions with us and
            the Services, the choices you make, and the products and features
            you use. The personal information we collect may include the
            following:
          </p>

          <ul className="list-disc pl-6 mb-4 text-gray-700">
            <li className="mb-2">email addresses</li>
            <li className="mb-2">phone numbers</li>
          </ul>

          <p className="mb-6 text-gray-700">
            Sensitive Information. We do not process sensitive information. All
            personal information that you provide to us must be true, complete,
            and accurate, and you must notify us of any changes to such personal
            information.
          </p>

          {/* Additional sections would follow the same structure */}
          {/* For brevity, I'm showing just the first section as a template */}
          {/* You can continue adding sections following the same format */}

          <h2 className="text-xl font-gilroy-semibold text-primary-dark mt-8 mb-4">
            10. HOW CAN YOU CONTACT US ABOUT THIS NOTICE?
          </h2>

          <p className="font-medium mb-2 text-gray-800">
            If you have questions or comments about this notice, you may contact
            us by post at:
          </p>

          <div className="bg-gray-50 p-4 rounded-lg mb-6">
            <p className="text-gray-700">
              Ramhar Agri
              <br />
              Chintamani Market, West of BSNL Golumber, Hajipur,
              <br />
              Vaishali, Bihar 844101
              <br />
              India
            </p>
          </div>

          <h2 className="text-xl font-gilroy-semibold text-primary-dark mt-8 mb-4">
            11. HOW CAN YOU REVIEW, UPDATE, OR DELETE THE DATA WE COLLECT FROM
            YOU?
          </h2>

          <p className="mb-4 text-gray-700">
            Based on the applicable laws of your country, you may have the right
            to request access to the personal information we collect from you,
            details about how we have processed it, correct inaccuracies, or
            delete your personal information. You may also have the right to
            withdraw your consent to our processing of your personal
            information. These rights may be limited in some circumstances by
            applicable law. To request to review, update, or delete your
            personal information, please fill out and submit a data subject
            access request @ https://
            app.termly.io/notify/cb540d13-c153-43e2-860d-7d824b77d10d
          </p>
        </div>
      </div>
    </div>
  );
};

export default Privacy;
